### ISSUE TITLE
Simplex noise not renderfarm safe

### ISSUE THREAD

**Issue by noouch** [Bercon/BerconMaps#1]
The simplex 3D function seems to misbehave somewhat between render machines, seemingly finding new random values each time, especially where XY coordinates < 0.

Example files:
simplexBug.max 660 KB
https://mega.co.nz/#!jkIxjC6Q!QR3GEqOR4PC3jQ8xaK3CMb2d5qQANfQOf5CZkCoY13c

In this video, a render job was submitted to the farm with packets of 3 being assigned to each machine:
simplexBug.mov 221 KB
https://mega.co.nz/#!CtJmyTLY!irfocYgfESBQWL3_NuBbVrjw8yf0G2IKjWTs4Bet2H0

**Comment by StrobFX** [comment]
Hi all. I can confirm this bug. I got dancing noise when I render on my farm with vray 3 and max 2015. This is sad cause I would really want to use bercon noise on all my productions but with this bug it is almost unusable. A solution would be to bake every bercon maps with render to texture everytime but it's such a burden that I prefer creating my textures in a paint app instead until this bug is fixed..

**Comment by GeorgeR** [comment]
We were getting these errors too, so I recompiled without fast-math and it seems to have fixed it. I'm not sure what other repercussions this has.

**Comment by StrobFX** [comment]
Hi. GeorgeR. I don't know how to recompile anything. Could you share your version here?

**Comment by GeorgeR** [comment]
Done - this incorporates the latest pull request (that hasn't been merged) and the precision thing:
https://www.dropbox.com/s/rdinttpvmqya3cf/BerconMaps_2015_64.zip?dl=0

**Comment by Bercon** [comment]
I haven't touched C++ or this project for ages, but if I remember correctly there was silly amount of macros used in the noise code that I had problems previously. Those should probably be turned into real functions and it might fix this issue. If somebody has more time to investigate this, it'd be appreciated.

**Comment by StrobFX** [comment]
Thanks a lot!

**Comment by GeorgeR** [comment]
Is anyone able to confirm if this was fixed? On my end, the test cases I had were ok.
