### ISSUE TITLE
Missing header-Files in BerconCommon.h

### ISSUE THREAD

**Issue by EdenCerberus** [Bercon/BerconMaps#10]
Hi,

at first thank You for Your work.

I want to compile this solution in VS2015/VS2017 but there a many missing files in BerconCommon.h.
Will there be a updated .sln for download with all the files or have I done something wrong?

Best regards!

**Comment by yavor-rubenov** [comment]
What files are missing ?
If they are Max.h, iparamb2.h etc - probably you haven't set a path to MaxSDK ?
