### ISSUE TITLE
Bump invert

### ISSUE THREAD

**Issue by orsgah** [Bercon/BerconMaps#11]
bump chanal inverting in color slot 2 if random 90 180 and flip tiling, the straght texture is fine but when roteted o fliped, bump inverted.

**Comment by feathered-arch** [comment]
In Noise? or another map?

Can you provide a screenshot of what's happening? 

(yes, I realize this is over 2 years old)

**Comment by orsgah** [comment]
In BerconTile, when using radomisation tile by mirror, some bump map invert

**Comment by feathered-arch** [comment]
Sorry, I am unable to reproduce. Can you upload a file where this is happening?

**Comment by orsgah** [comment]
It was long time ago)) I found that problem happend when i use as map CGSource Multitexture with option "Randomize by - Bercon tile" and put it into bump map on my material. And Bump map randomly flips when in bercon tile use Enable tile mapping with Random flip xy-axis, if Random flip xy-axis do not use, all work fine
