### ISSUE TITLE
3dsmax 2022 error

### ISSUE THREAD

**Issue by inafaracutiei** [Bercon/BerconMaps#35]
for some reason on 3dsmax 2022 i get this error, is there something i need to install, like a library or its a bug?

![image](https://user-images.githubusercontent.com/82023493/113679543-8beb2080-96c8-11eb-8d62-d632779a48d0.png)

**Comment by spencerskeen** [comment]
I am having the same problem. Brand new machine, clean  install Max 2022.1 Update.

**Comment by inafaracutiei** [comment]
it started to work after i updated max 2022 and windows to latest updates. But i'm not sure if it started to work after i installed windows visual C++ redistributable 2015-2019 also. I know one of these 3 factors came into play and it just worked

**Comment by feathered-arch** [comment]
It's likely the Visual C++ reinstall. The plugin for 2022 indirectly relies upon the Visual C++ 2015 toolkit, and therefore, the 2015 redist. runtime.

Please remember to mark the issue as closed.

**Comment by spencerskeen** [comment]
For me it was the Visual C++ install that sorted the issue.

**Comment by tokomod** [comment]
hi, I have installed on 3dmax 2023.1 and it shows same window. have windows 10, also have installed latest Visual C++. Im doing something wrong?
![1](https://user-images.githubusercontent.com/110623360/182898323-0782432a-42a1-49cc-944b-bd906a44cded.JPG)
