### ISSUE TITLE
Max 2020 - Error code 193

### ISSUE THREAD

**Issue by stephen147** [Bercon/BerconMaps#36]
I've downloaded the **BerconMaps_2020_64.dlt** for 2020 here: https://github.com/Bercon/BerconMaps/tree/master/src/DLL

**And I get this error**

![image](https://user-images.githubusercontent.com/14054664/130233599-6c43631e-15c0-4b54-a8b8-ef5a2505bd82.png)

**I've placed the .dll file in**

C:\Program Files\Autodesk\3ds Max 2020\Plugins

**I've tried installing the lastest vc_redist.x64.exe from here also**
https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0

**Comment by feathered-arch** [comment]
How did you download this? Did you right-click on the file to download, or did you click on BerconMaps_2020_64.dlt and then use the 'Download' button?

The latter is the correct method. You will end up with completely different files if you right-click to download.

**Comment by stephen147** [comment]
Thank you. The was the cause. I right clicked to download it.
