### ISSUE TITLE
BerconMaps not found

### ISSUE THREAD

**Issue by andrelung** [Bercon/BerconMaps#38]
Sorry, this might be a noob question. I am new to 3D and I took over a project that used BerconMaps before. I installed the 2020 dlt to my Plugins-Folder, but when starting up the project, I receive a Missing Dlls message (attached).
![bercon-not-found](https://user-images.githubusercontent.com/4161059/140487260-b655672f-b13c-4dc7-bdae-f79e48461cb4.PNG)

Not sure what's the problem here. I tried googling, but haven't found anything. Renaming the 2020-file to 2010 did not work either. Any nudge or hint is highly appreciated. Thank you very much!

**Comment by Bercon** [comment]
Download the correct version for your 3dsmax from https://github.com/Bercon/BerconMaps/tree/master/src/DLL

However, 2010 is so old, it might be from the first iteration of the plugin which is incompatible with the current version.

**Comment by andrelung** [comment]
Thanks for answering! I actually downloaded the 2020-Version, but it is not recognized by 3DSmax 2020. The above error keeps showing up. Any idea why that is? The scene has been built in 2020, so it should have run before.
