### ISSUE TITLE
it can import to blender?

### ISSUE THREAD

**Issue by manuelsongokuh** [Bercon/BerconMaps#4]
hello
it can import to blender?

**Comment by Bercon** [comment]
This is strictly 3dsmax plugin at the moment. The pattern logic is fairly separate so porting this to blender shouldn't be that huge task. I believe there was somebody trying to do that, however I don't think it was ever finished.

**Comment by manuelsongokuh** [comment]
ok please let me know news ok? blender is open source is easy to create addons ok? thank you!
