### ISSUE TITLE
error code 193 Max 2023.1

### ISSUE THREAD

**Issue by tokomod** [Bercon/BerconMaps#40]
hi, I have installed on 3dmax 2023.1 and it shows same window. have windows 10, also have installed latest Visual C++. Im doing something wrong
![1](https://user-images.githubusercontent.com/110623360/182900644-444f2a29-4330-4550-9a0e-28832b207043.JPG)
?

**Comment by tokomod** [comment]
same with 3dmax 2023 ( not 2023.1)

**Comment by tokomod** [comment]
dont know why, but from here it doesnt work for me. 
But from this topic I've downloaded and it worked. dont know why... 
here https://forums.chaos.com/forum/v-ray-for-3ds-max-forums/v-ray-for-3ds-max-general/1144605-berconmaps-compiled-for-max-2023

**Comment by yavor-rubenov** [comment]
Are you going to the folder with all the versions ([https://github.com/Bercon/BerconMaps/tree/master/src/DLL]), right clicking on the one you want and saving ? If so - that won't work. You need to left click on the file you want - it will take you to another page and there you have 'Download' button.
