### ISSUE TITLE
Compatibility with 3ds Max 2025

### ISSUE THREAD

**Issue by LoganAC34** [Bercon/BerconMaps#53]
This plugin needs updated to be compatible with 3ds max 2025. If you try to use the 2024 version, you'll get this error.

"DLL <C:\Program Files\Autodesk\3ds Max 2025\PlugIns\BerconMaps_2024_64.dlt> is not made for this version of the program - not "

**Comment by Bercon** [comment]
Fixed in https://github.com/Bercon/BerconMaps/pull/54
