### ISSUE TITLE
Problems with Windows10

### ISSUE THREAD

**Issue by Geddo** [Bercon/BerconMaps#7]
Even after installing the Microsoft Visual C++ 2005 SP1 Redistributable Package (and after rebooting obv.) Max will start with an error. Any chance to fix this? I'd love to use berconmaps with my new system

**Comment by yavor-rubenov** [comment]
Can you post a screen shot of the error you are getting? 
Also - what is your Max version?

**Comment by emesetot** [comment]
Hi! I have also problem with this. I have win 10 and MAx 2017. The pic of the error message:
![err](https://user-images.githubusercontent.com/32141330/30659010-d8bda14a-9e3c-11e7-98f3-24151c7fe7f5.png)
Please help me,  I really would like to use this. Thank you very much.

**Comment by emesetot** [comment]
Oh sorry I forget to mention I use the last version from the package : BerconMaps_2015_64

**Comment by yavor-rubenov** [comment]
Looking at the message - you are trying to use the plugin for Max 2015 in Max 2017. You should download BerconMaps_2017_64.dlt

**Comment by emesetot** [comment]
Sorry. But I just find this package and it is not included the newer one. Where can I find it? Can you link me please? And I am so sorry bec I am not so good with this.

**Comment by yavor-rubenov** [comment]
The plugins for the different Max versions are here:
[https://github.com/Bercon/BerconMaps/tree/master/src/DLL](https://github.com/Bercon/BerconMaps/tree/master/src/DLL)

And the plugin for Max 2017 is this one:
[https://github.com/Bercon/BerconMaps/raw/master/src/DLL/BerconMaps_2017_64.dlt](https://github.com/Bercon/BerconMaps/raw/master/src/DLL/BerconMaps_2017_64.dlt)

**Comment by emesetot** [comment]
Thank you very much. I really cant use this github. Tomorrow I will try to downlad. Thanks. And so so sorry.

**Comment by yavor-rubenov** [comment]
No problem. If you are still facing problems - do write back :)
